[package]
name = "iron-age-data"
version = "0.1.0"
edition = "2021"

[dependencies]
iron-age-core = { path = "../core" }
iron-age-inventory = { path = "../inventory" }
iron-age-character = { path = "../character" }
iron-age-combat = { path = "../combat" }
serde = { workspace = true }
rand = { workspace = true }
